"""Firewall ruleset parsing and policy auditing."""

from __future__ import annotations

from redteam_toolkit.modules import firewall_audit as fw

IPTABLES = """\
# Generated by iptables-save v1.8.7
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3306 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 5432 -s 10.0.0.0/8 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3389 -j DROP
-A INPUT -j DROP
COMMIT
"""

OPEN_BY_DEFAULT = """\
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
"""

RATE_LIMITED = """\
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --set
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 6 -j DROP
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
"""

LOGGED = IPTABLES.replace(
    "-A INPUT -j DROP",
    '-A INPUT -m limit --limit 5/min --limit-burst 10 -j LOG --log-prefix "dropped: " --log-level 4\n-A INPUT -j DROP',
)

NFT = """\
table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;
        ct state established,related accept
        iif lo accept
        tcp dport 22 accept
        tcp dport 443 accept
    }
}
"""

UFW = """\
Status: active
Default: deny (incoming), allow (outgoing), disabled (routed)
To                         Action      From
22/tcp                     ALLOW       Anywhere
80/tcp                     ALLOW       Anywhere
3306/tcp                   ALLOW       Anywhere
5432/tcp                   ALLOW       10.0.0.0/8
"""

FIREWALLD = """\
public (active)
  target: default
  services: ssh dhcpv6-client
  ports: 8080/tcp
  masquerade: no
"""


def write(tmp_path, text: str, name: str = "fw.txt"):
    path = tmp_path / name
    path.write_text(text, encoding="utf-8")
    return path


class TestBackendDetection:
    def test_iptables_is_detected(self, tmp_path):
        assert fw.parse(write(tmp_path, IPTABLES)).backend == "iptables"

    def test_nft_is_detected(self, tmp_path):
        assert fw.parse(write(tmp_path, NFT)).backend == "nftables"

    def test_ufw_is_detected(self, tmp_path):
        assert fw.parse(write(tmp_path, UFW)).backend == "ufw"

    def test_firewalld_is_detected(self, tmp_path):
        assert fw.parse(write(tmp_path, FIREWALLD)).backend == "firewalld"

    def test_unknown_input_is_reported(self, tmp_path):
        ruleset = fw.parse(write(tmp_path, "this is not a ruleset\njust some text\n"))
        assert ruleset.backend == "unknown"
        assert ruleset.warnings


class TestIptablesParsing:
    def test_policies_and_rules_are_read(self, tmp_path):
        ruleset = fw.parse(write(tmp_path, IPTABLES))
        assert ruleset.policies["INPUT"] == "DROP"
        assert len(ruleset.rules) == 9

    def test_jump_target_is_the_action(self, tmp_path):
        """-m match and -p protocol appear before -j, so tokens[0] is not the action."""
        ruleset = fw.parse(write(tmp_path, IPTABLES))
        actions = {r.action for r in ruleset.rules}
        assert actions == {"ACCEPT", "DROP"}

    def test_ports_and_sources_are_extracted(self, tmp_path):
        ruleset = fw.parse(write(tmp_path, IPTABLES))
        by_port = {r.dport: r for r in ruleset.rules if r.dport != "-"}
        assert by_port["22"].protocol == "tcp"
        assert by_port["22"].source == "-"
        assert by_port["22"].is_world_inbound
        assert by_port["5432"].source == "10.0.0.0/8"
        assert not by_port["5432"].is_world_inbound

    def test_equals_form_options_are_parsed(self, tmp_path):
        ruleset = fw.parse(
            write(
                tmp_path,
                "*filter\n:INPUT DROP [0:0]\n-A INPUT -p tcp --dport=8443 -s 10.0.0.5 -j ACCEPT\nCOMMIT\n",
            )
        )
        rule = ruleset.rules[0]
        assert rule.dport == "8443"
        assert rule.source == "10.0.0.5"

    def test_stateful_and_loopback_rules_are_classified(self, tmp_path):
        ruleset = fw.parse(write(tmp_path, IPTABLES))
        assert ruleset.rules[0].is_stateful
        assert ruleset.rules[1].is_loopback

    def test_exposed_ports_are_derived(self, tmp_path):
        ruleset = fw.parse(write(tmp_path, IPTABLES))
        exposed = ruleset.exposed_ports()
        assert set(exposed) == {22, 80, 443, 3306}


class TestPortExpansion:
    def test_single_port(self):
        assert fw._expand_ports("22") == [22]

    def test_port_list(self):
        assert fw._expand_ports("80,443") == [80, 443]

    def test_port_range(self):
        assert fw._expand_ports("8000-8002") == [8000, 8001, 8002]

    def test_wildcards_produce_nothing(self):
        assert fw._expand_ports("-") == []
        assert fw._expand_ports("") == []


class TestAudit:
    def test_default_drop_is_credited(self, tmp_path):
        report = fw.audit(str(write(tmp_path, IPTABLES)))
        assert any(f.check == "fw.default-drop" for f in report.findings)

    def test_default_accept_is_critical(self, tmp_path):
        """An ACCEPT default on a filtering chain makes the firewall documentation."""
        report = fw.audit(str(write(tmp_path, OPEN_BY_DEFAULT)))
        finding = next(f for f in report.findings if f.check == "fw.default-accept")
        assert finding.severity == "critical"
        assert "INPUT" in finding.evidence["policies"]

    def test_accept_output_policy_is_not_flagged(self, tmp_path):
        """An ACCEPT output policy is correct: a host must be able to make requests."""
        report = fw.audit(str(write(tmp_path, IPTABLES)))
        assert not any(f.check == "fw.default-accept" for f in report.findings)

    def test_world_reachable_sensitive_ports_are_flagged(self, tmp_path):
        report = fw.audit(str(write(tmp_path, IPTABLES)))
        exposed = {f.evidence["port"]: f.severity for f in report.findings if f.check == "fw.world-reachable"}
        assert exposed[3306] == "high"
        assert 5432 not in exposed  # scoped to 10.0.0.0/8

    def test_ssh_without_rate_limiting_is_flagged(self, tmp_path):
        report = fw.audit(str(write(tmp_path, IPTABLES)))
        assert any(f.check == "fw.ssh-no-rate-limit" for f in report.findings)

    def test_recent_module_is_credited(self, tmp_path):
        report = fw.audit(str(write(tmp_path, RATE_LIMITED)))
        assert any(f.check == "fw.ssh-recent" for f in report.findings)
        assert not any(f.check == "fw.ssh-no-rate-limit" for f in report.findings)

    def test_missing_logging_is_flagged(self, tmp_path):
        report = fw.audit(str(write(tmp_path, IPTABLES)))
        assert any(f.check == "fw.no-logging" for f in report.findings)

    def test_logging_is_credited(self, tmp_path):
        report = fw.audit(str(write(tmp_path, LOGGED)))
        assert any(f.check == "fw.logging" for f in report.findings)

    def test_stateful_return_is_detected(self, tmp_path):
        report = fw.audit(str(write(tmp_path, IPTABLES)))
        assert any(f.check == "fw.stateful-return" for f in report.findings)

    def test_missing_stateful_return_is_flagged(self, tmp_path):
        ruleset_text = (
            "*filter\n:INPUT DROP [0:0]\n-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT\n-A INPUT -j DROP\n"
        )
        report = fw.audit(str(write(tmp_path, ruleset_text)))
        assert any(f.check == "fw.no-stateful-return" for f in report.findings)

    def test_stateful_accept_does_not_shadow_later_drops(self, tmp_path):
        """A REAL bug this suite exists to prevent.

        An ESTABLISHED,RELATED accept never matches a new inbound connection, so
        it cannot shadow a later drop. Flagging it as a rule-ordering problem
        would be a false positive on every correctly configured host.
        """
        report = fw.audit(str(write(tmp_path, IPTABLES)))
        assert any(f.check == "fw.rule-order-ok" for f in report.findings)

    def test_broad_accept_before_narrow_drop_is_flagged(self, tmp_path):
        ruleset_text = (
            "*filter\n:INPUT DROP [0:0]\n"
            "-A INPUT -j ACCEPT\n"
            "-A INPUT -p tcp -m tcp --dport 3389 -s 10.0.0.0/8 -j DROP\n"
            "COMMIT\n"
        )
        report = fw.audit(str(write(tmp_path, ruleset_text)))
        assert any(f.check == "fw.rule-order" for f in report.findings)

    def test_wildcard_accept_is_critical(self, tmp_path):
        ruleset_text = "*filter\n:INPUT DROP [0:0]\n-A INPUT -j ACCEPT\nCOMMIT\n"
        report = fw.audit(str(write(tmp_path, ruleset_text)))
        assert any(f.check == "fw.wildcard-accept" for f in report.findings)

    def test_nft_ruleset_is_audited(self, tmp_path):
        report = fw.audit(str(write(tmp_path, NFT)))
        assert report.data["backend"] == "nftables"
        assert any(f.check == "fw.world-reachable" for f in report.findings)

    def test_ufw_ruleset_is_audited(self, tmp_path):
        report = fw.audit(str(write(tmp_path, UFW)))
        assert report.data["backend"] == "ufw"
        exposed = {f.evidence["port"] for f in report.findings if f.check == "fw.world-reachable"}
        assert 3306 in exposed
        assert 5432 not in exposed

    def test_firewalld_ruleset_is_audited(self, tmp_path):
        report = fw.audit(str(write(tmp_path, FIREWALLD)))
        assert report.data["backend"] == "firewalld"

    def test_unknown_backend_is_reported(self, tmp_path):
        report = fw.audit(str(write(tmp_path, "nonsense\nmore nonsense\n" * 20)))
        assert any(f.check == "fw.unknown-backend" for f in report.findings)

    def test_missing_file_is_reported_with_the_right_command(self, tmp_path):
        report = fw.audit(str(tmp_path / "absent.txt"))
        finding = next(f for f in report.findings if f.check == "fw.dump-missing")
        assert "iptables-save" in finding.remediation

    def test_report_serialises(self, tmp_path):
        import json

        json.loads(fw.audit(str(write(tmp_path, IPTABLES))).to_json())
